trigger:
  - master
  - releases/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install mkdocs-material
  displayName: 'Install dependencies'

- checkout: self

- script: |
    cd docs
    mkdocs gh-deploy --force
  displayName: 'Deploy to GitHub Pages'
