site_name: CloseAi Docs
theme:
  name: material
  features:
      - collapse_navigation
      - navigation.tabs
      - navigation.expand
      - navigation.sections
      - toc.integrate
      - navigation.top
      - search.suggest
      - search.highlight
      - content.tabs.link
      - content.code.annotation
      - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: blue
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: blue
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/vd9900/Ai-QA-System-with-docs
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/vd99O0
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/willettjames/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/vd9900"  target="_blank" rel="noopener">Vinith Devadiga</a>
