site_name: CloseAi Docs
theme:
  name: material
  logo: "https://th.bing.com/th/id/R.31a25011c7a2db24ad7d6ecfc6898ce7?rik=mt%2fggtk5uxFQbw&riu=http%3a%2f%2fc93fea60bb98e121740fc38ff31162a8.s3.amazonaws.com%2fwp-content%2fuploads%2f2017%2f03%2fdatarobot.jpg&ehk=P0IVwUi3%2boq1gaoV7unDcGw58WlR9j3yHzS1OLhLVhU%3d&risl=&pid=ImgRaw&r=0"
  logo_height: 50
  logo_width: 50
  features:
    - collapse_navigation
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en




  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: blue
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: blue
      accent: lime

extra_css:
  - custom.css


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/vd9900/Ai-QA-System-with-docs
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MR_VD9900
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/vinith-devadiga-79a342231/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/mr.vd9900
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


copyright: |
  &copy; 2023 <a href="https://github.com/vd9900"  target="_blank" rel="noopener">Vinith Devadiga</a>
